name: CI (backend básico)

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test-backend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install deps do projeto + pytest
        run: |
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi
          pip install pytest

      - name: Rodar testes (backend)
        run: pytest -q tests/test_tratar_urls.py

      - name: Gerar output.csv (headless)
        run: python scripts/generate_output.py

      - name: Conferir se output.csv existe
        run: test -f output.csv || (echo "output.csv não foi gerado" && exit 1)

      - name: Upload do output.csv
        uses: actions/upload-artifact@v4
        with:
          name: output
          path: output.csv
